export const SEARCHED_MOVIES_REQUEST = 'SEARCHED_MOVIES_REQUEST';
export const SEARCHED_MOVIES_SUCCESS = 'SEARCHED_MOVIES_SUCCESS';
export const ADD_MOVIE = 'ADD_MOVIE';
export const IS_LOADING = 'IS_LOADING';
